name: 'Tests & Linter'

on:
  pull_request:
    branches:
    - master

jobs:
  tests:
    name: 'Runs tests'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Installs packages'
      run: yarn

    - name: 'Runs linter'
      run: yarn lint

    - name: 'Runs tests'
      run: yarn test
