name: 'Tests'

on:
  pull_request:
    branches:
    - master

jobs:
  tests:
    name: 'Runs tests'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Verifies environment'
      run: yarn

    - name: 'Run tests'
      run: yarn test
